services:
  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - target: 8000
        published: 80
        mode: host
      - target: 8443
        published: 443
        mode: host
      - target: 8001
        published: 8001
        mode: host
      - target: 8444
        published: 8444
        mode: host
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - internal_net

  marketdb:
    image: postgres:16.2
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: marketdb
      POSTGRES_PASSWORD: market123
    volumes:
      - marketdb_data:/var/lib/postgresql/data
    networks:
      - database_net
      - adminer_db_net

  adminer:
    image: adminer
    ports:
      - target: 8080
        published: 8085
        mode: host
    networks:
      - adminer_db_net
      - internal_net

  user-service:
    image: user_service_image
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - internal_net
      - backend_net

  market-service:
    image: market_service_image
    build:
      context: ./market-service
      dockerfile: Dockerfile
    networks:
      - internal_net
      - backend_net

  io-service:
    image: io_service_image
    build:
      context: ./io-service
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=marketdb
      - DB_PASS=market123
      - DB_URL=jdbc:postgresql://marketdb:5432/marketdb
      - DB_USER=marketdb
    networks:
      - database_net
      - backend_net

volumes:
  marketdb_data:

networks:
  backend_net:
    driver: overlay
  internal_net:
    driver: overlay
  database_net:
    driver: overlay
  adminer_db_net:
    driver: overlay
