services:
  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - target: 8000
        published: 80
        mode: host
      - target: 8443
        published: 443
        mode: host
      - target: 8001
        published: 8001
        mode: host
      - target: 8444
        published: 8444
        mode: host
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - internal_net

  marketdb:
    image: postgres:16.2
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: marketdb
      POSTGRES_PASSWORD: market123
    volumes:
      - marketdb_data:/var/lib/postgresql/data
    networks:
      - database_net
      - adminer_db_net
    
  keycloakdb:
    image: postgres:16.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloakdb_data:/var/lib/postgresql/data
    networks:
      - keycloak_net
      - adminer_db_net
  
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    ports:
      - target: 8080
        published: 9090
        mode: host
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 9090
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - keycloakdb
    networks:
      - internal_net
      - keycloak_net

  adminer:
    image: adminer
    ports:
      - target: 8080
        published: 8085
        mode: host
    networks:
      - adminer_db_net
      - internal_net
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - target: 9443
        published: 9443
        mode: host
      - target: 9000
        published: 9000
        mode: host
    networks:
      - internal_net
    
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - target: 9090
        published: 9091
        mode: host
    networks:
      - backend_net
      - internal_net

  grafana:
    image: grafana/grafana:latest
    volumes:
    - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - target: 3000
        published: 9092
        mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - backend_net
      - internal_net

  user-service:
    image: user_service_image
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8090
        mode: host
    environment:
      - DB_HOSTNAME=marketdb
      - DB_PASS=market123
      - DB_URL=jdbc:postgresql://marketdb:5432/marketdb
      - DB_USER=marketdb
      - KEYCLOAK_ISSUER=http://localhost:9090/realms/marketplace-realm # For now for local testing
      - KEYCLOAK_JWK=http://keycloak:8080/realms/marketplace-realm/protocol/openid-connect/certs
      - JWT_RESOURCE_ID=marketplace-client
      - JWT_PRINCIPLE_ATTR=sub
    networks:
      - internal_net
      - backend_net
      - database_net
      - keycloak_net

  market-service:
    image: market_service_image
    build:
      context: ./market-service
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8089
        mode: host
    environment:
      - KEYCLOAK_ISSUER=http://localhost:9090/realms/marketplace-realm # For now for local testing
      - KEYCLOAK_JWK=http://keycloak:8080/realms/marketplace-realm/protocol/openid-connect/certs
      - JWT_RESOURCE_ID=marketplace-client
      - JWT_PRINCIPLE_ATTR=sub
    networks:
      - internal_net
      - backend_net
      - database_net

  io-service:
    image: io_service_image
    build:
      context: ./io-service
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=marketdb
      - DB_PASS=market123
      - DB_URL=jdbc:postgresql://marketdb:5432/marketdb
      - DB_USER=marketdb
    networks:
      - database_net
      - backend_net

volumes:
  marketdb_data:
  keycloakdb_data:
  portainer_data:

networks:
  backend_net:
    driver: overlay
  internal_net:
    driver: overlay
  database_net:
    driver: overlay
  adminer_db_net:
    driver: overlay
  keycloak_net:
    driver: overlay
