spring.application.name=user-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK}

jwt.auth.converter.resource-id=${JWT_RESOURCE_ID}
jwt.auth.converter.principle-attribute=${JWT_PRINCIPLE_ATTR}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.example.userservice=DEBUG
logging.level.org.springframework.security=DEBUG
