spring.application.name=user-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK}

jwt.auth.converter.resource-id=${JWT_RESOURCE_ID}
jwt.auth.converter.principle-attribute=${JWT_PRINCIPLE_ATTR}

logging.level.com.example.userservice=DEBUG
logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}

springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=false

springdoc.swagger-ui.oauth.client-id=marketplace-client
springdoc.swagger-ui.oauth.realm=marketplace-realm

server.forward-headers-strategy=framework

springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8081/oauth2-redirect.html
springdoc.openapi.servers[0].url=http://localhost:8000
springdoc.openapi.servers[0].description=Kong Gateway ENTRYPOINT
